name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: python:3.9.7-alpine3.14
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: pip install -r requirements/test.txt
      - name: Run tests
        run: pytest -vv
